// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcBeH2rWuFcfpTeY_qxl36-NwsItTBLsU',
    appId: '1:619160155813:web:571526366dd5aace40bf4c',
    messagingSenderId: '619160155813',
    projectId: 'fir-crud-app-59448',
    authDomain: 'fir-crud-app-59448.firebaseapp.com',
    storageBucket: 'fir-crud-app-59448.appspot.com',
    measurementId: 'G-PPVGZ5B4T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfElvy5Y0vlMsyhGWZTLrlPHJF8l5038s',
    appId: '1:619160155813:android:5cb6b040c008ea5440bf4c',
    messagingSenderId: '619160155813',
    projectId: 'fir-crud-app-59448',
    storageBucket: 'fir-crud-app-59448.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABd8xSPXm1mm4w_b-2hS1ku8h-kL9RYyU',
    appId: '1:619160155813:ios:68918626e03753c440bf4c',
    messagingSenderId: '619160155813',
    projectId: 'fir-crud-app-59448',
    storageBucket: 'fir-crud-app-59448.appspot.com',
    iosBundleId: 'com.example.firebaseCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABd8xSPXm1mm4w_b-2hS1ku8h-kL9RYyU',
    appId: '1:619160155813:ios:68918626e03753c440bf4c',
    messagingSenderId: '619160155813',
    projectId: 'fir-crud-app-59448',
    storageBucket: 'fir-crud-app-59448.appspot.com',
    iosBundleId: 'com.example.firebaseCrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcBeH2rWuFcfpTeY_qxl36-NwsItTBLsU',
    appId: '1:619160155813:web:ab4cd09abe0ff3e340bf4c',
    messagingSenderId: '619160155813',
    projectId: 'fir-crud-app-59448',
    authDomain: 'fir-crud-app-59448.firebaseapp.com',
    storageBucket: 'fir-crud-app-59448.appspot.com',
    measurementId: 'G-E58SDCV5EW',
  );
}
